version: '3'
services:
  updater:
    image: maxmindinc/geoipupdate
    environment:
      GEOIPUPDATE_ACCOUNT_ID: 111111
      GEOIPUPDATE_LICENSE_KEY: xxxxxxxxx
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country GeoLite2-City
      GEOIPUPDATE_FREQUENCY: 2
      GEOIPUPDATE_VERBOSE: 1
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    volumes:
      - /opt/geoip/:/usr/share/GeoIP/:Z
